### ISSUE TITLE
Feat: 앱 출시를 위한 변경사항

### ISSUE THREAD

**Issue by RuyHa** [kko-okk/kko_okk#206]
전에 팀원 초대를 위한 작업을 하면서 번들 아이디에  -가 들어가면 안되는 이슈를 찾아서 
앱 첫 버전 업데이트를 위해 변경 사항이 조금 씩 있을 것 같습니다.
브랜치를 파서 작업을 하도록 하겠습니다.

**Comment by RuyHa** [comment]
AppStoreSet 이라는 이름으로 데브에서 브랜치 파서 작업 하겠습니다.

**Comment by garlicvread** [comment]
오 드디어........ 류하 개므시쪙!!!
