### ISSUE TITLE
Refacoring : 온보딩 리팩토링

### ISSUE THREAD

**Issue by RuyHa** [kko-okk/kko_okk#212]
작업시 기존 온보딩을 선제거 하면 문제가 생길 수 있으니
NewOnboarding으로 작업후 추후 기존 온보딩 제거하겠습니다.

**Comment by RuyHa** [comment]
7.10 14:00 작업시작

**Comment by RuyHa** [comment]
레이몬드가 작업하신 관계로 이슈클로즈 하겠습니다

**Comment by garlicvread** [comment]
> 레이몬드가 작업하신 관계로 이슈클로즈 하겠습니다

사랑해요
