### ISSUE TITLE
Refactor: 온보딩용 세그먼트 뷰의 커스텀 디바이더 작업

### ISSUE THREAD

**Issue by garlicvread** [kko-okk/kko_okk#235]

**Comment by garlicvread** [comment]
[Refactor] 온보딩용 세그먼트 뷰의 커스텀 디바이더 작성

- 현재 온보딩을 실제 사용 화면과 유사하게 변경 중
- 세그먼트와 아래 위시 리스트, 프로미스 리스트가 렌더되는 TodoBoardView를 나누는 디바이더를 커스텀하는 중
- 원본 코드에도 GeomertyReader를 사용한 부분이 있기는 한데, 왠지 작동을 잘 안해서 새로 작성이 필요

**Comment by yeniful** [comment]
이슈 컨벤션 지켜주세요!

**Comment by garlicvread** [comment]
@yeniful 맞게 쓰고 있지 않나용?

**Comment by garlicvread** [comment]
#240 으로 완료했습니당
이슈 닫습니다.
