### ISSUE TITLE
Feat: CI/CD 적용

### ISSUE THREAD

**Issue by garlicvread** [kko-okk/kko_okk#243]
Git Action 등을 통해 쉽고 간편하게 앱을 빌드하고 오류를 테스트할 수 있는 환경 설정이 필요함

**Comment by yeniful** [comment]
이슈 컨벤션 지켜주세요

**Comment by yeniful** [comment]
지속적 통합, 지속적 배포는 합의가 되지 않은 부분같습니다

**Comment by garlicvread** [comment]
이슈 컨벤션은 따로 없었던 걸로 알고 있습니다

**Comment by garlicvread** [comment]
그리고 CI/CD 적용은 반드시 필요한 부분이니 추가적으로 회의가 있었음 하네요

**Comment by yeniful** [comment]
<img width="1047" alt="스크린샷 2022-07-29 오후 2 30 54" src="https://user-images.githubusercontent.com/77262576/181689185-fe4f377e-410a-48fa-b0fb-62188b20f1e8.png">

**Comment by yeniful** [comment]
문서에는 없지만 구두로 지키자고 합의했던 것으로 기억합니다

**Comment by yeniful** [comment]
CI CD는 배포 이후에 논의하면 좋을 것 같아요

**Comment by garlicvread** [comment]
> CI CD는 우선순위 후선위로 배포 이후에 논의하면 좋을 것 같아요

맞습니다! 이건 저희 MVP 내용이 아니고 먼 훗날 이야기입니다.
그러나 한 번 회의는 해 보는 게 좋을 것 같았어요.

**Comment by garlicvread** [comment]
CI/CD 관련 이슈는 시간이 조금 더 소요될 것으로 판단되어 이슈 닫겠습니다.
나중에 더 논의해 봐요!
